version: 2.1
# workflows:
#   testing:
#     jobs:
#       - runner-test
# jobs:
#   runner-test:
#     machine: true
#     resource_class: datslife/circleci
#     steps:
#       - run: echo "Hi I'm on Runners!444"
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo "Thanh cong roi moi nguoi oi!!!+333"

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: main # only deploy on the main branch琀
